networks:   
    app-tier:
        driver: bridge
        
services:
    db:
        container_name: database
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: world
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: password
            MYSQL_ROOT_HOST: '%'

        build: db/
        ports:
            - 3306:3306
        networks:
            - app-tier 

    web:
        container_name: web_app
        build: .
        ports:
            - 3000:3002
        volumes:
            - .:/code
        networks:
            - app-tier
        depends_on:
            - db
